# PCEBookShop Configuration File

economy:
  # Possible Providers: economyapi, multieconomy, xp
  provider: economyapi
  # This is used for the MultiEconomy provider
  multieconomy-currency: ""

cost:
  # If you are using xp provider, 1 = 1 level of experience.
  common: 1000
  uncommon: 2500
  rare: 5000
  mythic: 10000

chance:
  # Gamma for weighting levels. Higher gamma = lower change of high-level books.
  # Tests: https://gist.github.com/Aericio/856c9b54f98af2164ce8600c5be3eb17
  gamma: 1.5

excluded-enchants:
  - "placeholder"
